[package]
name = "llhttp_sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.147"

[build-dependencies]
cc = "1.0.82"
bindgen = "0.69.1"
